### ISSUE TITLE
セッション切れ時に認証する公式サイトログインページからログインできない

### ISSUE THREAD

**Issue by Osarumonky** [ryouEin/vrchat-friend-instance-list#164]
症状の概要：
「VRChat Friend Instance List」のFirefox版（4.0.2）にてVRChat公式サイトのセッション切れ時に案内されるログインページからのログインができなくなっています。
詳細は分かりませんが、ログインURLを「 https://vrchat.com/home 」に変えるとログインできるという情報がありました。
もし可能でしたら対応頂けたら幸いです。

エラー詳細：
2021/03/07　22：00ごろから、
ブラウザ上で「 https://www.vrchat.com/home/login 」経由でのログインが全体的に不調になっています。その影響でVRChat Friend Instance Listのセッション認証も不可能な状態になってしまっています。
具体的には、IDとパスワードを正しく入力しても
「Internal Server Error: Session- is running a version 5‚ but the database version is 6」
というエラーが返ってきてログインをすることができません。

回避策：
詳細や仕組みについては未確認ですがVRChatのブラウザ認証にて、
「https://vrchat.com/home/」
を使うとブラウザ版VRChatにログインできるとの情報があります。
（報告者も実際にログインできました。）
そのため、もし可能なようでしたら対応頂けたら幸いです

参考URL：
https://twitter.com/xlwnya/status/1368109095513825282

（いつも使用させて頂いております。イベントのインスタンス管理に大変助かっています！！）

**Comment by ryouEin** [comment]
ご報告ありがとうございます！
当該エラーですが、現在VRChat側の修正により解決しておりますのでこちらは閉じさせて頂きます。

今回はVRChat側の修正ですぐ解決しましたが、そうでない場合も多くこういう形での不具合報告は非常に助かります。
また何かあればご報告頂ければとても嬉しいです！
